# Generated by Django 3.2.6 on 2021-08-09 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(default='Pomoika', on_delete=django.db.models.deletion.CASCADE, to='main.organization'),
            preserve_default=False,
        ),
    ]
