# Generated by Django 3.2.6 on 2021-08-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_report_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='text',
            new_name='report_details',
        ),
        migrations.AddField(
            model_name='report',
            name='danger_level',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
