# Generated by Django 3.2.6 on 2021-08-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210810_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'SEO'), (1, 'Manager'), (2, 'Worker')], null=True),
        ),
    ]
