# Generated by Django 3.2.6 on 2021-08-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_message_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
